### ISSUE TITLE
Unable to install duckietown world on Computer

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/duckietown-world#8]
I am trying to set up the duckietown-world and I am getting following error in the installation step:
```

alessandro: ~/duckietown/duckietown-world [master18]$ python setup.py develop --no-deps
running develop
running egg_info
writing src/duckietown_world.egg-info/PKG-INFO 
error: [Errno 13] Permission denied: 'src/duckietown_world.egg-info/PKG-INFO''
```

Operating System: native Ubuntu 16.04

My src/duckietown_world.egg-info/PKG-INFO file looks like the following:

```
Metadata-Version: 1.1
Name: duckietown-world
Version: 1.0.15
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Download-URL: http://github.com/duckietown/duckietown-world/tarball/1.0.15
Description: UNKNOWN
Platform: UNKNOWN
```

When I try to do the DEMO anyway I get following console output:

```
(base)  alessandro: ~/aaa_duckietown/duckietown-world [master18|✔]$ make tests-clean tests
rm -rf out-comptests out-coverage .coverage .coverage.*
comptests --nonose duckietown_world_tests
WARNING:comptests:PyContracts disabled for speed. Use --contracts to activate.
INFO:contracts:All contracts checking disabled.
Creating storage in out-comptests/compmake with compress False
Reading configuration from '.compmake.rc'.                                           
INFO:comptests:Setting output dir to out-comptests/
INFO:conf_tools:loaded global config dir 'default'
INFO:comptests:Interpreting 'duckietown_world_tests' as module.
INFO:comptests:Creating reports
___ duckietown_world_tests-comptests ________________________________________________
 comptests|   comptests.py:182  - instance_comptests_jobs2_m| Could not import m     
odule 'duckietown_world_tests'                                                       
Job 'duckietown_world_tests-comptests' failed:                                       
| Exception: Could not import module 'duckietown_world_tests'                        
| | Cannot import name 'duckietown_world_tests'.                                     
| |   > Traceback (most recent call last):                                           
| |   >   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/conf_tools/instantiate_utils.py", line 41, in import_name
| |   >     return __import__(name, fromlist=['dummy'])                              
| |   > ModuleNotFoundError: No module named 'duckietown_world_tests'                
| |   >                                                                              
| | sys_path: Instance of <class 'list'>.                                            
| |           ['/home/alessandro/anaconda3/bin', '/home/alessandro/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/home/alessandro/anaconda3/lib/python37.zip', '/home/alessandro/anaconda3/lib/python3.7', '/home/alessandro/anaconda3/lib/python3.7/lib-dynload', '/home/alessandro/anaconda3/lib/python3.7/site-packages']
> Traceback (most recent call last):                                                 
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/conf_tools/instantiate_utils.py", line 41, in import_name
>     return __import__(name, fromlist=['dummy'])                                    
> ModuleNotFoundError: No module named 'duckietown_world_tests'                      
>                                                                                    
> During handling of the above exception, another exception occurred:                
>                                                                                    
> Traceback (most recent call last):                                                 
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/comptests/comptests.py", line 176, in instance_comptests_jobs2_m
>     module = import_name(module_name)                                              
>   File "<decorator-gen-739>", line 2, in import_name                               
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/contracts/main.py", line 243, in contracts_checker
>     return function_(*args, **kwargs)                                              
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/conf_tools/instantiate_utils.py", line 91, in import_name
>     raise_desc(ValueError, msg, sys_path=sys.path)                                 
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/contracts/utils.py", line 215, in raise_desc
>     raise etype(s)                                                                 
> ValueError: Cannot import name 'duckietown_world_tests'.                           
>   > Traceback (most recent call last):                                             
>   >   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/conf_tools/instantiate_utils.py", line 41, in import_name
>   >     return __import__(name, fromlist=['dummy'])                                
>   > ModuleNotFoundError: No module named 'duckietown_world_tests'                  
>   >                                                                                
> sys_path: Instance of <class 'list'>.                                              
>           ['/home/alessandro/anaconda3/bin', '/home/alessandro/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/home/alessandro/anaconda3/lib/python37.zip', '/home/alessandro/anaconda3/lib/python3.7', '/home/alessandro/anaconda3/lib/python3.7/lib-dynload', '/home/alessandro/anaconda3/lib/python3.7/site-packages']
>                                                                                    
> During handling of the above exception, another exception occurred:                
>                                                                                    
> Traceback (most recent call last):                                                 
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/compmake/jobs/actions.py", line 249, in make
>     result = job_compute(job=job, context=context)                                 
>   File "<decorator-gen-28>", line 2, in job_compute                                
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/contracts/main.py", line 243, in contracts_checker
>     return function_(*args, **kwargs)                                              
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/compmake/jobs/job_execution.py", line 56, in job_compute
>     command=command, args=args, kwargs=kwargs)                                     
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/compmake/jobs/job_execution.py", line 103, in execute_with_context
>     res = command(*args, **kwargs)                                                 
>   File "<decorator-gen-844>", line 2, in _dynreports_wrap_dynamic                  
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/contracts/main.py", line 243, in contracts_checker
>     return function_(*args, **kwargs)                                              
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/quickapp/compmake_context.py", line 356, in _dynreports_wrap_dynamic
>     res['f-result'] = function(qc, *args, **kw)                                    
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/quickapp/compmake_context.py", line 339, in wrap_state_dynamic
>     return f(context, *args, **kwargs)                                             
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/comptests/comptests.py", line 184, in instance_comptests_jobs2_m
>     raise_wrapped(Exception, e, msg)                                               
>   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/contracts/utils.py", line 172, in raise_wrapped
>     raise e                                                                        
> Exception: Could not import module 'duckietown_world_tests'                        
> | Cannot import name 'duckietown_world_tests'.                                     
> |   > Traceback (most recent call last):                                           
> |   >   File "/home/alessandro/anaconda3/lib/python3.7/site-packages/conf_tools/instantiate_utils.py", line 41, in import_name
> |   >     return __import__(name, fromlist=['dummy'])                              
> |   > ModuleNotFoundError: No module named 'duckietown_world_tests'                
> |   >                                                                              
> | sys_path: Instance of <class 'list'>.                                            
> |           ['/home/alessandro/anaconda3/bin', '/home/alessandro/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/home/alessandro/anaconda3/lib/python37.zip', '/home/alessandro/anaconda3/lib/python3.7', '/home/alessandro/anaconda3/lib/python3.7/lib-dynload', '/home/alessandro/anaconda3/lib/python3.7/site-packages']
Write "details duckietown_world_tests-comptests" to inspect the error.               
Processed 6 jobs (1 done, 1 failed, 4 blocked).                                      
Makefile:34: recipe for target 'tests' failed
make: *** [tests] Error 2

```

What would be the desired output?

**Comment by lapandic** [comment]
@alessandromorra please create a virtualenv and try to install it inside.

**Comment by AndreaCensi** [comment]
@alessandromorra the problem is the permission error: 
```
error: [Errno 13] Permission denied: 'src/duckietown_world.egg-info/PKG-INFO''
```

You used root when you should not have. Need to change those permissions (or burn everything and do from scratch.)
